qhse/Controllers/GestionStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using qhse.Models;

namespace qhse.Controllers
{
    public class GestionStatusController : BaseController
    {
        private readonly RavinalaEntities db = new RavinalaEntities();

        // GET: StatusAdmin
        public ActionResult Index()
        {
            return View(db.Status.ToList());
        }

        // GET: StatusAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StatusAdmin/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NOM_STATUS")] StatutModele statutmodele)
        {
            if (ModelState.IsValid)
            {
                Status status = new Status
                {
                    NOM_STATUS = statutmodele.NOM_STATUS
                };
                db.Status.Add(status);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(statutmodele);
        }

        // GET: StatusAdmin/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Status.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            StatutModele statutmodele = new StatutModele
            {
                ID_STATUS = status.ID_STATUS,
                NOM_STATUS = status.NOM_STATUS
            };
            return View(statutmodele);
        }

        // POST: StatusAdmin/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_STATUS,NOM_STATUS")] StatutModele statutmodele)
        {
            if (ModelState.IsValid)
            {
                Status status = new Status
                {
                    ID_STATUS = statutmodele.ID_STATUS,
                    NOM_STATUS = statutmodele.NOM_STATUS
                };
                db.Entry(status).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(statutmodele);
        }

        // POST: StatusAdmin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Status.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            db.Status.Remove(status);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

qhse/Views/GestionStatus/Create.cshtml
@model qhse.Models.StatutModele
@{
    ViewBag.Title = "Ajout statut";
    ViewBag.Gestion = "active";
    ViewBag.Status = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion statuts
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li><a href="@Url.Action("Index", "GestionStatus")">Gestion statuts</a></li>
            <li class="active">Ajout</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Ajout</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (@Html.BeginForm("Create", "GestionStatus", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.NOM_STATUS, "Désignation", htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.EditorFor(model => model.NOM_STATUS, new { htmlAttributes = new { @class = "form-control", @placeholder = "Statut" } })
                            @Html.ValidationMessageFor(model => model.NOM_STATUS, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="text-danger text-center">@ViewBag.Message</div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index")">
                        <button type="button" class="btn btn-primary">Annuler</button>
                    </a>
                    <button type="submit" class="btn btn-success pull-right">Ajouter</button>
                </div>
                <!-- /.box-footer -->
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

qhse/Views/GestionStatus/Edit.cshtml
@model qhse.Models.StatutModele
@{
    ViewBag.Title = "Modification statut";
    ViewBag.Gestion = "active";
    ViewBag.Status = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion statuts
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li><a href="@Url.Action("Index", "GestionStatus")">Gestion statuts</a></li>
            <li class="active">Modification</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Modification</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (@Html.BeginForm("Edit", "GestionStatus", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                <div class="box-body">
                    @Html.HiddenFor(model => model.ID_STATUS)
                    <div class="form-group">
                        @Html.LabelFor(model => model.NOM_STATUS, "Désignation", htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.EditorFor(model => model.NOM_STATUS, new { htmlAttributes = new { @class = "form-control", @placeholder = "Statu" } })
                            @Html.ValidationMessageFor(model => model.NOM_STATUS, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="text-danger text-center">@ViewBag.Message</div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index")">
                        <button type="button" class="btn btn-primary">Annuler</button>
                    </a>
                    <button type="submit" class="btn btn-warning pull-right">Modifier</button>
                </div>
                <!-- /.box-footer -->
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

qhse/Views/GestionStatus/Index.cshtml
@model IEnumerable<qhse.Models.Status>
@{
    ViewBag.Title = "Gestion statuts";
    ViewBag.Gestion = "active";
    ViewBag.Status = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion statuts
            <a href="@Url.Action("Create", "GestionStatus")">
                <small>
                    <span class="label label-success">
                        <i class="fa fa-user-plus"></i> Ajouter
                    </span>
                </small>
            </a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li class="active">Gestion statuts</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title"><button type="button" class="btn btn-block btn-default btn-sm">Retour</button></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-header">
                        <h3 class="box-title"><button type="button" class="btn btn-block btn-default btn-sm">Retour</button></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tr>
                                <th>Statut</th>
                                <th>Action</th>
                            </tr>
                            @foreach (var item in Model)
                            {
                                var modal = "modal-delete" + item.ID_STATUS;
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NOM_STATUS)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "GestionStatus", new { id = item.ID_STATUS })">
                                            <span class="label label-primary">
                                                <i class="fa fa-edit"></i> Edit
                                            </span>
                                        </a>
                                        &nbsp;
                                        <a href="#" data-toggle="modal" data-target="#@modal">
                                            <span class="label label-danger">
                                                <i class="fa fa-user-times"></i> Delete
                                            </span>
                                        </a>
                                        <div class="modal modal-danger fade" id="@modal">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        <h4 class="modal-title">Confirmation</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Etes-vous sûr de vouloire supprimer le compte @item.NOM_STATUS?</p>
                                                    </div>
                                                    @using (Html.BeginForm("Delete", "GestionStatus", new { id = item.ID_STATUS }, FormMethod.Post))
                                                    {
                                                        @Html.AntiForgeryToken()
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Annuler</button>
                                                            <button type="submit" class="btn btn-outline">Oui</button>
                                                        </div>
                                                    }
                                                </div>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                        </div>
                                        <!-- /.modal -->
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            <li><a href="#">&laquo;</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">&raquo;</a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.box -->

            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->