qhse/Controllers/GestionComptesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using qhse.Models;
using System.Net;


namespace qhse.Controllers
{
    public class GestionComptesController : BaseController
    {
        private readonly RavinalaEntities db = new RavinalaEntities();

        // GET: GestionCompte
        public ActionResult Index()
        {
            var user = db.User.Include(u => u.Status);
            return View(user.ToList());
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.ID_STATUS = new SelectList(db.Status, "ID_STATUS", "NOM_STATUS");
            return View();
        }

        // POST: Users/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_STATUS,USERNAME,PASSWORD,CPASSWORD")] UserModele usermodele)
        {
            if (ModelState.IsValid)
            {
                if (usermodele.PASSWORD != usermodele.CPASSWORD)
                {
                    ViewBag.Message = string.Format("Le mot de passe ne correspond pas au confirmation mot de passe!");
                    ViewBag.ID_STATUS = new SelectList(db.Status, "ID_STATUS", "NOM_STATUS", usermodele.ID_STATUS);
                    return View(usermodele);
                }
                User user = new User
                {
                    ID_STATUS = usermodele.ID_STATUS,
                    USERNAME = usermodele.USERNAME,
                    PASSWORD = usermodele.PASSWORD
                };
                db.User.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_STATUS = new SelectList(db.Status, "ID_STATUS", "NOM_STATUS", usermodele.ID_STATUS);
            return View(usermodele);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_STATUS = new SelectList(db.Status, "ID_STATUS", "NOM_STATUS", user.ID_STATUS);
            UserModele usermodele = new UserModele
            {
                ID_USER = user.ID_USER,
                ID_STATUS = user.ID_STATUS,
                USERNAME = user.USERNAME,
                PASSWORD = user.PASSWORD,
                CPASSWORD = user.PASSWORD
            };
            return View(usermodele);
        }

        // POST: Users/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_USER,ID_STATUS,USERNAME,PASSWORD,CPASSWORD")] UserModele usermodele)
        {
            if (ModelState.IsValid)
            {
                if (usermodele.PASSWORD != usermodele.CPASSWORD)
                {
                    ViewBag.Message = string.Format("Le mot de passe ne correspond pas au confirmation mot de passe!");
                    ViewBag.ID_STATUS = new SelectList(db.Status, "ID_STATUS", "NOM_STATUS", usermodele.ID_STATUS);
                    return View(usermodele);
                }
                User user = new User
                {
                    ID_USER = usermodele.ID_USER,
                    ID_STATUS = usermodele.ID_STATUS,
                    USERNAME = usermodele.USERNAME,
                    PASSWORD = usermodele.PASSWORD
                };
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_STATUS = new SelectList(db.Status, "ID_STATUS", "NOM_STATUS", usermodele.ID_STATUS);
            return View(usermodele);
        }

        // POST: Users/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            db.User.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Verouiller(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            if (user.LOCK == true)
            {
                user.LOCK = false;
            }
            else if (user.LOCK == false)
            {
                user.LOCK = true;
            }
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

qhse/Views/GestionComptes/Create.cshtml
@model qhse.Models.UserModele
@{
    ViewBag.Title = "Ajout compte";
    ViewBag.Gestion = "active";
    ViewBag.Compte = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion compte
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li><a href="@Url.Action("Index", "GestionComptes")">Gestion compte</a></li>
            <li class="active">Ajout</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Ajout</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (@Html.BeginForm("Create", "GestionComptes", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.USERNAME, htmlAttributes: new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control", @placeholder = "Pseudo" } })
                                @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_STATUS, "Status", htmlAttributes: new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.DropDownList("ID_STATUS", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ID_STATUS, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.PASSWORD, htmlAttributes: new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.PasswordFor(model => model.PASSWORD, new { @class = "form-control", placeholder = "Mot de passe" })
                                @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label"></label>
                            <div class="col-sm-10">
                                @Html.PasswordFor(model => model.CPASSWORD, new { @class = "form-control", placeholder = "Confirmation mot de passe" })
                                @Html.ValidationMessageFor(model => model.CPASSWORD, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="text-danger text-center">@ViewBag.Message</div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="@Url.Action("Index")">
                            <button type="button" class="btn btn-primary">Annuler</button>
                        </a>
                        <button type="submit" class="btn btn-success pull-right">Ajouter</button>
                    </div>
                    <!-- /.box-footer -->
             }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

qhse/Views/GestionComptes/Edit.cshtml
@model qhse.Models.UserModele
@{
    ViewBag.Title = "Modification compte";
    ViewBag.Gestion = "active";
    ViewBag.Compte = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion compte
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li><a href="@Url.Action("Index", "GestionComptes")">Gestion compte</a></li>
            <li class="active">Modification</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Modification</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (@Html.BeginForm("Edit", "GestionComptes", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                <div class="box-body">
                    @Html.HiddenFor(model => model.ID_USER)
                    <div class="form-group">
                        @Html.LabelFor(model => model.USERNAME, htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control", @placeholder = "Pseudo" } })
                            @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_STATUS, "Status", htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.DropDownList("ID_STATUS", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ID_STATUS, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PASSWORD, htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.PasswordFor(model => model.PASSWORD, new { @class = "form-control", placeholder = "Mot de passe" })
                            @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label"></label>
                        <div class="col-sm-10">
                            @Html.PasswordFor(model => model.CPASSWORD, new { @class = "form-control", placeholder = "Confirmation mot de passe" })
                            @Html.ValidationMessageFor(model => model.CPASSWORD, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="text-danger text-center">@ViewBag.Message</div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index")">
                        <button type="button" class="btn btn-primary">Annuler</button>
                    </a>
                    <button type="submit" class="btn btn-warning pull-right">Modifier</button>
                </div>
                <!-- /.box-footer -->
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

qhse/Views/GestionComptes/Index.cshtml
@model IEnumerable<qhse.Models.User>
@{
    ViewBag.Title = "Gestion compte";
    ViewBag.Gestion = "active";
    ViewBag.Compte = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion compte
            <a href="@Url.Action("Create", "GestionComptes")">
                <small>
                    <span class="label label-success">
                        <i class="fa fa-user-plus"></i> Ajouter
                    </span>
                </small>
            </a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li class="active">Gestion compte</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title"><button type="button" class="btn btn-block btn-default btn-sm">Retour</button></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-header">
                        <h3 class="box-title"><button type="button" class="btn btn-block btn-default btn-sm">Retour</button></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tr>
                                <th>Pseudo</th>
                                <th>Statut</th>
                                <th>Verrouillé</th>
                                <th>Action</th>
                            </tr>
                            @foreach (var item in Model)
                            {
                                var compte = item.USERNAME + "(" + item.Status.NOM_STATUS + ")";
                                var modal = "modal-delete" + item.ID_USER;
                                var modal2 = "modal-lock" + item.ID_USER;
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.USERNAME)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status.NOM_STATUS)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LOCK)
                            </td>
                            <td>
                                <a href="@Url.Action("Edit", "GestionComptes", new { id = item.ID_USER })">
                                    <span class="label label-primary">
                                        <i class="fa fa-edit"></i> Edit
                                    </span>
                                </a>
                                &nbsp;
                                <a href="#" data-toggle="modal" data-target="#@modal">
                                    <span class="label label-danger">
                                        <i class="fa fa-user-times"></i> Delete
                                    </span>
                                </a>
                                <div class="modal modal-danger fade" id="@modal">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                <h4 class="modal-title">Confirmation</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>Etes-vous sûr de vouloire supprimer le compte @compte?</p>
                                            </div>
                                            @using (Html.BeginForm("Delete", "GestionComptes", new { id = item.ID_USER }, FormMethod.Post))
                                            {
                                                @Html.AntiForgeryToken()
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Annuler</button>
                                                    <button type="submit" class="btn btn-outline">Oui</button>
                                                </div>
                                            }
                                        </div>
                                        <!-- /.modal-content -->
                                    </div>
                                    <!-- /.modal-dialog -->
                                </div>
                                <!-- /.modal -->
                                &nbsp;
                                <a href="#" data-toggle="modal" data-target="#@modal2">
                                    <span class="label label-warning">
                                        @{
                                            var fa = "";
                                            var text = "";
                                            if (item.LOCK == false)
                                            {
                                                fa = "fa-lock";
                                                text = "Verouiller";
                                            }
                                            else if (item.LOCK == true)
                                            {
                                                fa = "fa-unlock-alt";
                                                text = "Déverouiller";
                                            }
                                        }
                                        <i class="fa @fa"></i> @text
                                    </span>
                                </a>
                                <div class="modal modal-warning fade" id="@modal2">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                <h4 class="modal-title">Confirmation</h4>
                                            </div>
                                            <div class="modal-body">
                                                @{
                                                    var text2 = "";
                                                    if (item.LOCK == false)
                                                    {
                                                        text2 = "verouiller";
                                                    }
                                                    else if (item.LOCK == true)
                                                    {
                                                        text2 = "déverouiller";
                                                    }
                                                }
                                                <p>Etes-vous sûr de vouloire @text2 le compte @compte?</p>
                                            </div>
                                            @using (Html.BeginForm("Verouiller", "GestionComptes", new { id = item.ID_USER }, FormMethod.Post))
                                            {
                                                @Html.AntiForgeryToken()
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Annuler</button>
                                                    <button type="submit" class="btn btn-outline">Oui</button>
                                                </div>
                                            }
                                        </div>
                                        <!-- /.modal-content -->
                                    </div>
                                    <!-- /.modal-dialog -->
                                </div>
                                <!-- /.modal -->
                            </td>
                        </tr>
                            }
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            <li><a href="#">&laquo;</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">&raquo;</a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.box -->

            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->