qhse/Controllers/GestionRubriquesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using qhse.Models;

namespace qhse.Controllers
{
    public class GestionRubriquesController : BaseController
    {
        private readonly RavinalaEntities db = new RavinalaEntities();

        // GET: RubriquesAdmin
        public ActionResult Index()
        {
            var rubrique = db.Rubrique.Include(r => r.Section);
            return View(rubrique.ToList());
        }

        // GET: RubriquesAdmin/Create
        public ActionResult Create()
        {
            SelectList list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == null), "ID_SECTION", "NOM_SECTION");
            ViewBag.ID_SECTION = list.Prepend(new SelectListItem { Value = null });
            return View();
        }

        // POST: RubriquesAdmin/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_SECTION,NOM_RUBRIQUE,SEARCH,PARENT_SEC_ID_SECTION")] RubriqueModele rubriquemodele)
        {
            if (ModelState.IsValid && rubriquemodele.SEARCH == 0)
            {
                Rubrique rubrique = new Rubrique
                {
                    ID_SECTION = rubriquemodele.ID_SECTION,
                    NOM_RUBRIQUE = rubriquemodele.NOM_RUBRIQUE
                };
                db.Rubrique.Add(rubrique);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            SelectList list = null;
            if (rubriquemodele.SEARCH == 1)
            {
                if (rubriquemodele.ID_SECTION == 0)
                {
                    list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == null), "ID_SECTION", "NOM_SECTION");
                    rubriquemodele.PARENT_SEC_ID_SECTION = null;
                }
                else if (rubriquemodele.ID_SECTION != 0)
                {
                    list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == rubriquemodele.ID_SECTION), "ID_SECTION", "NOM_SECTION");
                    rubriquemodele.PARENT_SEC_ID_SECTION = rubriquemodele.ID_SECTION;
                }
                ModelState.Clear();
            }
            else if (rubriquemodele.SEARCH == 0)
            {
                list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == rubriquemodele.PARENT_SEC_ID_SECTION), "ID_SECTION", "NOM_SECTION", rubriquemodele.ID_SECTION);
            }
            ViewBag.ID_SECTION = list.Prepend(new SelectListItem { Value = null });
            return View(rubriquemodele);
        }

        // GET: RubriquesAdmin/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rubrique rubrique = db.Rubrique.Find(id);
            if (rubrique == null)
            {
                return HttpNotFound();
            }
            Section parentSec = db.Section.Where(Section => Section.ID_SECTION == rubrique.ID_SECTION).FirstOrDefault();
            if (parentSec == null)
            {
                parentSec = new Section { SEC_ID_SECTION = null };
            }
            RubriqueModele rubriquemodele = new RubriqueModele
            {
                ID_RUBRIQUE = rubrique.ID_RUBRIQUE,
                ID_SECTION = rubrique.ID_SECTION,
                NOM_RUBRIQUE = rubrique.NOM_RUBRIQUE,
                PARENT_SEC_ID_SECTION = parentSec.SEC_ID_SECTION
            };
            SelectList list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == rubriquemodele.PARENT_SEC_ID_SECTION), "ID_SECTION", "NOM_SECTION", rubrique.ID_SECTION);
            ViewBag.ID_SECTION = list.Prepend(new SelectListItem { Value = null });
            return View(rubriquemodele);
        }

        // POST: RubriquesAdmin/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_RUBRIQUE,ID_SECTION,NOM_RUBRIQUE,SEARCH,PARENT_SEC_ID_SECTION")] RubriqueModele rubriquemodele)
        {
            if (ModelState.IsValid && rubriquemodele.SEARCH == 0)
            {
                Rubrique rubrique = new Rubrique
                {
                    ID_RUBRIQUE = rubriquemodele.ID_RUBRIQUE,
                    ID_SECTION = rubriquemodele.ID_SECTION,
                    NOM_RUBRIQUE = rubriquemodele.NOM_RUBRIQUE
                };
                db.Entry(rubrique).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            SelectList list = null;
            if (rubriquemodele.SEARCH == 1)
            {
                if (rubriquemodele.ID_SECTION == 0)
                {
                    list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == null), "ID_SECTION", "NOM_SECTION");
                    rubriquemodele.PARENT_SEC_ID_SECTION = null;
                }
                else if (rubriquemodele.ID_SECTION != 0)
                {
                    list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == rubriquemodele.ID_SECTION), "ID_SECTION", "NOM_SECTION");
                    rubriquemodele.PARENT_SEC_ID_SECTION = rubriquemodele.ID_SECTION;
                }
                ModelState.Clear();
            }
            else if (rubriquemodele.SEARCH == 0)
            {
                list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == rubriquemodele.PARENT_SEC_ID_SECTION), "ID_SECTION", "NOM_SECTION", rubriquemodele.ID_SECTION);
            }
            ViewBag.ID_SECTION = list.Prepend(new SelectListItem { Value = null });
            return View(rubriquemodele);
        }

        // POST: RubriquesAdmin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rubrique rubrique = db.Rubrique.Find(id);
            if (rubrique == null)
            {
                return HttpNotFound();
            }
            db.Rubrique.Remove(rubrique);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

qhse/Views/GestionRubriques/Create.cshtml
@model qhse.Models.RubriqueModele
@{
    ViewBag.Title = "Ajout rubrique";
    ViewBag.Gestion = "active";
    ViewBag.Rubrique = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion rubriques
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li><a href="@Url.Action("Index", "GestionRubriques")">Gestion rubriques</a></li>
            <li class="active">Ajout</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Ajout</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (@Html.BeginForm("Create", "GestionRubriques", FormMethod.Post, new { @class = "form-horizontal", @id = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.SEARCH)
                @Html.HiddenFor(model => model.PARENT_SEC_ID_SECTION)
                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_SECTION, "SECTION", htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownList("ID_SECTION", null, htmlAttributes: new { @class = "form-control", @id = "dropdownlist" })
                            @Html.ValidationMessageFor(model => model.ID_SECTION, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-sm-1">
                            <button type="button" class="btn btn-block btn-primary btn-sm" id="btnsearch">Ok</button>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.NOM_RUBRIQUE, "Nom rubrique", htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-8">
                            @Html.EditorFor(model => model.NOM_RUBRIQUE, new { htmlAttributes = new { @class = "form-control", @placeholder = "Rubrique" } })
                            @Html.ValidationMessageFor(model => model.NOM_RUBRIQUE, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="text-danger text-center">@ViewBag.Message</div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index")">
                        <button type="button" class="btn btn-primary">Annuler</button>
                    </a>
                    <button type="button" class="btn btn-success pull-right" id="btnajout">Ajouter</button>
                </div>
                <!-- /.box-footer -->
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

qhse/Views/GestionRubriques/Edit.cshtml
@model qhse.Models.RubriqueModele
@{
    ViewBag.Title = "Gestion rubriques";
    ViewBag.Gestion = "active";
    ViewBag.Rubrique = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion rubriques
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li><a href="@Url.Action("Index", "GestionRubriques")">Gestion compte</a></li>
            <li class="active">Modification</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Modification</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (@Html.BeginForm("Edit", "GestionRubriques", FormMethod.Post, new { @class = "form-horizontal", @id = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.SEARCH)
                @Html.HiddenFor(model => model.PARENT_SEC_ID_SECTION)
                <div class="box-body">
                    @Html.HiddenFor(model => model.ID_RUBRIQUE)
                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_SECTION, "Section", htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownList("ID_SECTION", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ID_SECTION, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-sm-1">
                            <button type="button" class="btn btn-block btn-primary btn-sm" id="btnsearch">Ok</button>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.NOM_RUBRIQUE, htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-8">
                            @Html.EditorFor(model => model.NOM_RUBRIQUE, new { htmlAttributes = new { @class = "form-control", @placeholder = "Rubrique" } })
                            @Html.ValidationMessageFor(model => model.NOM_RUBRIQUE, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="text-danger text-center">@ViewBag.Message</div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index")">
                        <button type="button" class="btn btn-primary">Annuler</button>
                    </a>
                    <button type="button" class="btn btn-warning pull-right" id="btnajout">Modifier</button>
                </div>
                <!-- /.box-footer -->
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

qhse/Views/GestionRubriques/Index.cshtml
@model IEnumerable<qhse.Models.Rubrique>
@{
    ViewBag.Title = "Gestion rubriques";
    ViewBag.Gestion = "active";
    ViewBag.Rubrique = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion rubriques
            <a href="@Url.Action("Create", "GestionRubriques")">
                <small>
                    <span class="label label-success">
                        <i class="fa fa-user-plus"></i> Ajouter
                    </span>
                </small>
            </a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li class="active">Gestion rubriques</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title"><button type="button" class="btn btn-block btn-default btn-sm">Retour</button></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-header">
                        <h3 class="box-title"><button type="button" class="btn btn-block btn-default btn-sm">Retour</button></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tr>
                                <th>Nom rubrique</th>
                                <th>Section</th>
                                <th>Action</th>
                            </tr>
                            @foreach (var item in Model)
                            {
                                var modal = "modal-delete" + item.ID_RUBRIQUE;
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NOM_RUBRIQUE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Section.NOM_SECTION)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "GestionRubriques", new { id = item.ID_RUBRIQUE })">
                                            <span class="label label-primary">
                                                <i class="fa fa-edit"></i> Edit
                                            </span>
                                        </a>
                                        &nbsp;
                                        <a href="#" data-toggle="modal" data-target="#@modal">
                                            <span class="label label-danger">
                                                <i class="fa fa-user-times"></i> Delete
                                            </span>
                                        </a>
                                        <div class="modal modal-danger fade" id="@modal">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        <h4 class="modal-title">Confirmation</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Etes-vous sûr de vouloire supprimer le compte @item.NOM_RUBRIQUE?</p>
                                                    </div>
                                                    @using (Html.BeginForm("Delete", "GestionRubriques", new { id = item.ID_RUBRIQUE }, FormMethod.Post))
                                                    {
                                                        @Html.AntiForgeryToken()
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Annuler</button>
                                                            <button type="submit" class="btn btn-outline">Oui</button>
                                                        </div>
                                                    }
                                                </div>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                        </div>
                                        <!-- /.modal -->
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            <li><a href="#">&laquo;</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">&raquo;</a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.box -->

            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->