qhse/Controllers/GestionSectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using qhse.Models;

namespace qhse.Controllers
{
    public class GestionSectionsController : BaseController
    {
        private readonly RavinalaEntities db = new RavinalaEntities();

        // GET: SectionsAdmin
        public ActionResult Index()
        {
            var section = db.Section.Include(s => s.Section2);
            return View(section.ToList());
        }

        // GET: SectionsAdmin/Create
        public ActionResult Create()
        {
            SelectList list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == null), "ID_SECTION", "NOM_SECTION");
            ViewBag.SEC_ID_SECTION = list.Prepend(new SelectListItem { Value = null });
            return View();
        }

        // POST: SectionsAdmin/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SEC_ID_SECTION,NOM_SECTION,IconFile,AS_TABS,SEARCH,PARENT_SEC_ID_SECTION")] SectionModele sectionmodele)
        {
            if (ModelState.IsValid && sectionmodele.SEARCH == 0)
            {
                string directoryPath = Server.MapPath("~/dist/img/icon/");
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }
                string fileName = Path.GetFileName(sectionmodele.IconFile.FileName);
                string extension = Path.GetExtension(fileName);
                string nameWithoutExtension = Path.GetFileNameWithoutExtension(fileName);
                string path = Path.Combine(Server.MapPath("~/dist/img/icon/"), fileName);
                var i = 1;
                while (System.IO.File.Exists(path))
                {
                    fileName = nameWithoutExtension.Trim() + " (" + i + ")" + extension;
                    path = Path.Combine(Server.MapPath("~/dist/img/icon/"), fileName);
                    i++;
                }
                sectionmodele.IconFile.SaveAs(path);
                sectionmodele.ICONE = fileName;
                Section section = new Section
                {
                    SEC_ID_SECTION = sectionmodele.SEC_ID_SECTION,
                    NOM_SECTION = sectionmodele.NOM_SECTION,
                    ICONE = sectionmodele.ICONE,
                    AS_TABS = sectionmodele.AS_TABS
                };
                db.Section.Add(section);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            SelectList list = null;
            if (sectionmodele.SEARCH == 1)
            {
                list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == sectionmodele.SEC_ID_SECTION), "ID_SECTION", "NOM_SECTION");
                ModelState.Clear();
                sectionmodele.PARENT_SEC_ID_SECTION = sectionmodele.SEC_ID_SECTION;
            }
            else if (sectionmodele.SEARCH == 0)
            {
                list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == sectionmodele.PARENT_SEC_ID_SECTION), "ID_SECTION", "NOM_SECTION", sectionmodele.SEC_ID_SECTION);
            }
            ViewBag.SEC_ID_SECTION = list.Prepend(new SelectListItem { Value = null });
            return View(sectionmodele);
        }

        // GET: SectionsAdmin/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Section.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            Section parentSec = db.Section.Where(Section => Section.ID_SECTION == section.SEC_ID_SECTION).FirstOrDefault();
            if (parentSec == null)
            {
                parentSec = new Section { SEC_ID_SECTION = null };
            }
            SectionEditModele sectionmodele = new SectionEditModele
            {
                ID_SECTION = section.ID_SECTION,
                SEC_ID_SECTION = section.SEC_ID_SECTION,
                NOM_SECTION = section.NOM_SECTION,
                ICONE = section.ICONE,
                AS_TABS = section.AS_TABS,
                PARENT_SEC_ID_SECTION = parentSec.SEC_ID_SECTION
            };
            SelectList list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == sectionmodele.PARENT_SEC_ID_SECTION), "ID_SECTION", "NOM_SECTION", section.SEC_ID_SECTION);
            ViewBag.SEC_ID_SECTION = list.Prepend(new SelectListItem { Value = null });
            return View(sectionmodele);
        }

        // POST: SectionsAdmin/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_SECTION,SEC_ID_SECTION,NOM_SECTION,IconFile,ICONE,AS_TABS,SEARCH,PARENT_SEC_ID_SECTION")] SectionEditModele sectionmodele)
        {
            if (ModelState.IsValid && sectionmodele.SEARCH == 0 && sectionmodele.ID_SECTION != sectionmodele.SEC_ID_SECTION)
            {
                if (sectionmodele.IconFile != null)
                {
                    string directoryPath = Server.MapPath("~/dist/img/icon/");
                    if (!Directory.Exists(directoryPath))
                    {
                        Directory.CreateDirectory(directoryPath);
                    }
                    string fileName = Path.GetFileName(sectionmodele.IconFile.FileName);
                    string extension = Path.GetExtension(fileName);
                    string nameWithoutExtension = Path.GetFileNameWithoutExtension(fileName);
                    string path = Path.Combine(Server.MapPath("~/dist/img/icon/"), fileName);
                    var i = 1;
                    while (System.IO.File.Exists(path))
                    {
                        fileName = nameWithoutExtension.Trim() + " (" + i + ")" + extension;
                        path = Path.Combine(Server.MapPath("~/dist/img/icon/"), fileName);
                        i++;
                    }
                    sectionmodele.IconFile.SaveAs(path);
                    sectionmodele.ICONE = fileName;
                }

                Section section = new Section
                {
                    ID_SECTION = sectionmodele.ID_SECTION,
                    SEC_ID_SECTION = sectionmodele.SEC_ID_SECTION,
                    NOM_SECTION = sectionmodele.NOM_SECTION,
                    ICONE = sectionmodele.ICONE,
                    AS_TABS = sectionmodele.AS_TABS
                };
                db.Entry(section).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            SelectList list = null;
            if (sectionmodele.SEARCH == 1)
            {
                list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == sectionmodele.SEC_ID_SECTION), "ID_SECTION", "NOM_SECTION");
                ModelState.Clear();
                sectionmodele.PARENT_SEC_ID_SECTION = sectionmodele.SEC_ID_SECTION;
            }
            else if (sectionmodele.SEARCH == 0)
            {
                list = new SelectList(db.Section.Where(Section => Section.SEC_ID_SECTION == sectionmodele.PARENT_SEC_ID_SECTION), "ID_SECTION", "NOM_SECTION", sectionmodele.SEC_ID_SECTION);
            }
            if (sectionmodele.ID_SECTION == sectionmodele.SEC_ID_SECTION)
            {
                ViewBag.Message = "Une section ne peut pas être une sous section de lui même!";
            }
            ViewBag.SEC_ID_SECTION = list.Prepend(new SelectListItem { Value = null });
            return View(sectionmodele);
        }

        // POST: SectionsAdmin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(decimal id)
        {
            if (id.Equals(null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Section.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            db.Section.Remove(section);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

qhse/Views/GestionSections/Create.cshtml
@model qhse.Models.SectionModele
@{
    ViewBag.Title = "Ajout section";
    ViewBag.Gestion = "active";
    ViewBag.Section = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion sections
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li><a href="@Url.Action("Index", "GestionSections")">Gestion sections</a></li>
            <li class="active">Ajout</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Ajout</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (@Html.BeginForm("Create", "GestionSections", FormMethod.Post, new { @class = "form-horizontal", @id = "form", @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.SEARCH)
                @Html.HiddenFor(model => model.PARENT_SEC_ID_SECTION)
        <div class="box-body">
            <div class="form-group">
                @Html.LabelFor(model => model.SEC_ID_SECTION, "Section mère", htmlAttributes: new { @class = "col-sm-2 control-label" })
                <div class="col-sm-8">
                    @Html.DropDownList("SEC_ID_SECTION", null, htmlAttributes: new { @class = "form-control", @id = "dropdownlist" })
                    @Html.ValidationMessageFor(model => model.SEC_ID_SECTION, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-1">
                    <button type="button" class="btn btn-block btn-primary btn-sm" id="btnsearch">Ok</button>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NOM_SECTION, "Section", htmlAttributes: new { @class = "col-sm-2 control-label" })
                <div class="col-sm-8">
                    @Html.EditorFor(model => model.NOM_SECTION, new { htmlAttributes = new { @class = "col-sm-2 form-control", placeholder = "Section" } })
                    @Html.ValidationMessageFor(model => model.NOM_SECTION, "", new { @class = "text-danger" })
                </div>
            </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ICONE, htmlAttributes: new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.IconFile, new { type = "file" })
                        @Html.ValidationMessageFor(model => model.IconFile, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(model => model.AS_TABS, "Onglet", htmlAttributes: new { @class = "control-label col-sm-1" })
                    <div class="col-sm-3">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.AS_TABS)
                            @Html.ValidationMessageFor(model => model.AS_TABS, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="text-danger text-center">@ViewBag.Message</div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <a href="@Url.Action("Index")">
                    <button type="button" class="btn btn-primary">Annuler</button>
                </a>
                <button type="button" class="btn btn-success pull-right" id="btnajout">Ajouter</button>
            </div>
            <!-- /.box-footer -->
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

qhse/Views/GestionSections/Edit.cshtml
@model qhse.Models.SectionEditModele
@{
    ViewBag.Title = "Modification section";
    ViewBag.Gestion = "active";
    ViewBag.Section = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion sections
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li><a href="@Url.Action("Index", "GestionSections")">Gestion sections</a></li>
            <li class="active">Ajout</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Modification</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (@Html.BeginForm("Edit", "GestionSections", FormMethod.Post, new { @class = "form-horizontal", @id = "form", @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ID_SECTION)
                @Html.HiddenFor(model => model.ICONE)
                @Html.HiddenFor(model => model.SEARCH)
                @Html.HiddenFor(model => model.PARENT_SEC_ID_SECTION)
                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.SEC_ID_SECTION, "Section mère", htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownList("SEC_ID_SECTION", null, htmlAttributes: new { @class = "form-control", @id = "dropdownlist" })
                            @Html.ValidationMessageFor(model => model.SEC_ID_SECTION, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-sm-1">
                            <button type="button" class="btn btn-block btn-primary btn-sm" id="btnsearch">Ok</button>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.NOM_SECTION, "Section", htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-8">
                            @Html.EditorFor(model => model.NOM_SECTION, new { htmlAttributes = new { @class = "col-sm-2 form-control", placeholder = "Section" } })
                            @Html.ValidationMessageFor(model => model.NOM_SECTION, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ICONE, htmlAttributes: new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(model => model.IconFile, new { type = "file" })
                            @Html.ValidationMessageFor(model => model.IconFile, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.AS_TABS, "Onglet", htmlAttributes: new { @class = "control-label col-sm-1" })
                        <div class="col-sm-3">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.AS_TABS)
                                @Html.ValidationMessageFor(model => model.AS_TABS, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="text-danger text-center">@ViewBag.Message</div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index")">
                        <button type="button" class="btn btn-primary">Annuler</button>
                    </a>
                    <button type="button" class="btn btn-warning pull-right" id="btnajout">Modifier</button>
                </div>
                <!-- /.box-footer -->
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

qhse/Views/GestionSections/Index.cshtml
@model IEnumerable<qhse.Models.Section>
@{
    ViewBag.Title = "Gestion sections";
    ViewBag.Gestion = "active";
    ViewBag.Section = "active";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Gestion sections
            <a href="@Url.Action("Create", "GestionSections")">
                <small>
                    <span class="label label-success">
                        <i class="fa fa-user-plus"></i> Ajouter
                    </span>
                </small>
            </a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Accueil</a></li>
            <li class="active">Gestion sections</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title"><button type="button" class="btn btn-block btn-default btn-sm">Retour</button></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-header">
                        <h3 class="box-title"><button type="button" class="btn btn-block btn-default btn-sm">Retour</button></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tr>
                                <th>Icon</th>
                                <th>Nom section</th>
                                <th>Section mère</th>
                                <th>Onglet</th>
                                <th>Action</th>
                            </tr>
                            @foreach (var item in Model)
                            {
                                var modal = "modal-delete" + item.ID_SECTION;
                                <tr>
                                    <td>
                                        <img src="~/dist/img/icon/@Html.DisplayFor(modelItem => item.ICONE)" height="48px" class="figure-img img-fluid rounded">
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NOM_SECTION)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Section2.NOM_SECTION)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AS_TABS)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "GestionSections", new { id = item.ID_SECTION })">
                                            <span class="label label-primary">
                                                <i class="fa fa-edit"></i> Edit
                                            </span>
                                        </a>
                                        &nbsp;
                                        <a href="#" data-toggle="modal" data-target="#@modal">
                                            <span class="label label-danger">
                                                <i class="fa fa-user-times"></i> Delete
                                            </span>
                                        </a>
                                        <div class="modal modal-danger fade" id="@modal">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        <h4 class="modal-title">Confirmation</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Etes-vous sûr de vouloire supprimer le compte @item.NOM_SECTION?</p>
                                                    </div>
                                                    @using (Html.BeginForm("Delete", "GestionSections", new { id = item.ID_SECTION }, FormMethod.Post))
                                                    {
                                                        @Html.AntiForgeryToken()
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Annuler</button>
                                                            <button type="submit" class="btn btn-outline">Oui</button>
                                                        </div>
                                                    }
                                                </div>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                        </div>
                                        <!-- /.modal -->
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            <li><a href="#">&laquo;</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">&raquo;</a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.box -->

            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->